### PR TITLE
Add an option to install chrome or firefox

### PR DESCRIPTION
**Pull request by palewire**
I believe this will be necessary for me to workaround [this bug](https://github.com/microsoft/playwright/issues/13093#issuecomment-1081094858)

### CODE REVIEW

**Comment by simonw** [comment]
Love this. How will users pick which browser to run using Playwright if they have more than one installed?

**Comment by palewire** [comment]
Good question. I think we'd maybe need another option for the run command huh?

**Comment by simonw** [comment]
Yeah adding `--browser` to the `shot` and `multi` and `javascript` and `pdf` and `accessibility` commands would do the trick.

**Comment by simonw** [comment]
Actually maybe not `accessibility` and `pdf` since I think those only work with Chromium.

**Comment by palewire** [comment]
I've drafted an implementation that starts out by adding firefox. It appears to work in my testing. Let me know what you think. I'm looking at a Chrome extension to this next.

**Comment by palewire** [comment]
Okay I think I got chrome in there now too.

**Pull request merged**
